[project]
name = "djangoproject"
version = "0.1.0"
description = ""
authors = [
    {name = "Daniil Korobko",email = "“korobko_01@inbox.ru”"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0,<7.0)",
    "psycopg (>=3.3.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
